# IMPORTING PACKAGES

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import re
from nltk.stem import PorterStemmer
from nltk.tokenize import sent_tokenize, word_tokenize

In [2]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Mohit\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Mohit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

# READING THE DATA

In [3]:
train = pd.read_csv('train.csv',encoding='latin1')

In [4]:
train.drop('ItemID',axis=1,inplace=True)

In [5]:
train.head()

Sentiment                                      SentimentText
0          0                       is so sad for my APL frie...
1          0                     I missed the New Moon trail...
2          1                            omg its already 7:30 :O
3          0            .. Omgaga. Im sooo  im gunna CRy. I'...
4          0           i think mi bf is cheating on me!!!   ...

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99989 entries, 0 to 99988
Data columns (total 2 columns):
Sentiment        99989 non-null int64
SentimentText    99989 non-null object
dtypes: int64(1), object(1)
memory usage: 1.5+ MB


In [7]:
train['Sentiment'].value_counts()

1    56457
0    43532
Name: Sentiment, dtype: int64

# DATA CLEANING

In [8]:
#removal of urls
def rem_url(col):
    text=col[0]
    text=re.sub(r'http\S+',"",text)
    return text
train[['SentimentText']]=train[['SentimentText']].apply(rem_url,axis=1)

In [9]:
#removal of usernames
def rem_user(col):
    text=col[0]
    text=re.sub(r'@[A-Za-z0-9_]{1,15}',"",text)
    return text
train[['SentimentText']]=train[['SentimentText']].apply(rem_user,axis=1)

In [10]:
#removal of special characters
def rem_special(col):
    text=col[0]
    text=re.sub(r'[^A-Za-z0-9]+'," ",text)
    return text
train[['SentimentText']]=train[['SentimentText']].apply(rem_special,axis=1)

In [11]:
#removal of spaces from start and end
def rem_space(col):
    text=col[0]
    text.strip()
    return text
train[['SentimentText']]=train[['SentimentText']].apply(rem_space,axis=1)

In [12]:
#removal of digits
def rem_dig(col):
    text=col[0]
    text=re.sub(r'\d+',"",text)
    return text
train[['SentimentText']]=train[['SentimentText']].apply(rem_dig,axis=1)

In [13]:
#conversion to lowercase
def con_tolower(col):
    text=col[0]
    text=text.lower()
    return text
train[['SentimentText']]=train[['SentimentText']].apply(con_tolower,axis=1)

In [14]:
train.head(50)

Sentiment                                      SentimentText
0           0                       is so sad for my apl friend 
1           0                     i missed the new moon trailer 
2           1                                omg its already   o
3           0   omgaga im sooo im gunna cry i ve been at this...
4           0                i think mi bf is cheating on me t t
5           0                          or i just worry too much 
6           1                  juuuuuuuuuuuuuuuuussssst chillin 
7           0               sunny again work tomorrow tv tonight
8           1      handed in my uniform today i miss you already
9           1                  hmmmm i wonder how she my number 
10          0                       i must think about positive 
11          1   thanks to all the haters up in my face all day  
12          0                     this weekend has sucked so far
13          0             jb isnt showing in australia any more 
14          0                               ok thats it you win 
15          0               lt this is the way i feel right now 
16          0   awhhe man i m completely useless rt now funny...
17          1   feeling strangely fine now i m gonna go liste...
18          0            huge roll of thunder just now so scary 
19          0   i just cut my beard off it s only been growin...
20          0                               very sad about iran 
21          0                                      wompppp wompp
22          1   you re the only one who can see this cause no...
23          0   lt sad level is  i was writing a massive blog...
24          0   headed to hospitol had to pull out of the gol...
25          0        boring whats wrong with him please tell me 
26          0   can t be bothered i wish i could spend the re...
27          0   feeeling like shit right now i really want to...
28          1               goodbye exams hello alcohol tonight 
29          0   i didn t realize it was that deep geez give a...
30          0   i hate it when any athlete appears to tear an...
31          0   i miss you guys too i think i m wearing skinn...
32          0                                    meet your meat 
33          0           my horsie is moving on saturday morning 
34          0              no sat off need to work  days a week 
35          0   really dont like doing my room its so boring ...
36          0   sox floyd was great but relievers need a scol...
37          0                            times by like a million
38          1                  uploading pictures on friendster 
39          0   what type of a spaz downloads a virus my brot...
40          0                   amp amp fightiin wiit the babes 
41          1   so i wrote something last week and i got a ca...
42          0                                       enough said 
43          1   do i need to even say it do i well here i go ...
44          1                          health class what a joke 
45          1                         lt  go to the show tonight
46          0   it really makes me sad when i look at muslims...
47          0   all time low shall be my motivation for the r...
48          0   and the entertainment is over someone complai...
49          0   another year of lakers that s neither magic n...

# TOKENIZATION AND STEMMING

In [15]:
ps=PorterStemmer()
from nltk.corpus import stopwords

In [16]:
train.shape[0]

99989

In [17]:
corpus = []
for i in range(0,99989):
    tweet = train['SentimentText'][i]
    tweet = tweet.split()
    tweet = [ps.stem(word) for word in tweet if not word in set(stopwords.words('english'))]
    tweet = ' '.join(tweet)
    corpus.append(tweet)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

In [19]:
cv=CountVectorizer(max_features=2500)

In [20]:
X=cv.fit_transform(corpus).toarray()

In [21]:
y=np.asarray(train['Sentiment'])

In [22]:
y

array([0, 0, 1, ..., 0, 1, 1], dtype=int64)

# SPLITTING TRAIN TEST DATA

In [23]:
from sklearn.cross_validation import train_test_split

C:\Users\Mohit\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [24]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.3,random_state=0)

# FITTING CLASSIFICATION MODELS

In [25]:
from sklearn.naive_bayes import GaussianNB

In [26]:
model = GaussianNB()

In [27]:
model.fit(X_train,y_train)

GaussianNB(priors=None)

In [28]:
predictions=model.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix,classification_report

In [30]:
cm=confusion_matrix(y_test,predictions)

In [32]:
print(cm)

[[ 7872  5288]
 [ 4507 12330]]


In [33]:
cr=classification_report(y_test,predictions)

In [34]:
print(cr)

             precision    recall  f1-score   support

          0       0.64      0.60      0.62     13160
          1       0.70      0.73      0.72     16837

avg / total       0.67      0.67      0.67     29997



In [35]:
#using randomforest
from sklearn.ensemble import RandomForestClassifier

In [43]:
model1=RandomForestClassifier(n_estimators=100)

In [44]:
model1.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [45]:
predictions1=model1.predict(X_test)

In [46]:
cm1=confusion_matrix(y_test,predictions1)

In [47]:
print(cm1)

[[ 8705  4455]
 [ 3839 12998]]


In [48]:
cr1=classification_report(y_test,predictions1)

In [49]:
print(cr1)

             precision    recall  f1-score   support

          0       0.69      0.66      0.68     13160
          1       0.74      0.77      0.76     16837

avg / total       0.72      0.72      0.72     29997

